description = "Développeur Java, Spring & co, et fier de l'être"
introDescription = "Développeur Java, Spring & co, et fier de l'être."
introURL = "about/"
enableSearch = true
mainSections = ["posts"]
blogDir = "posts"
usePageBundles = false
codeMaxLines = 7
codeLineNumbers = false
numberOfTagsShown = 20
numberOfRecentPosts = 10
dateFormat = "2 January 2006"
since = 2012
comments = true
logo = "wp-content/uploads/2013/12/banniere_java_et_moi_1260x240.png"
centerLogo = true
showShare = true
pinFeatured = false

# Google Analytics Id
ga_analytics = "G-SH8Q845WZ2"

[author]
name = "Java & Moi"
photo = "wp-content/uploads/2012/02/JavaOne2000.jpg"
