#!/usr/bin/env python3
"""Generate static redirect pages for legacy WordPress taxonomy URLs.

WordPress used /tag/<slug>/ and /category/<slug>/ while Hugo uses
/tags/<slug>/ and /categories/<slug>/.  Category slugs also differ
because WordPress stripped accents while Hugo keeps them.

The generated HTML files are placed under static/tag/ and static/category/
so that Hugo copies them into the build output automatically.

Usage:
    python3 scripts/generate_wordpress_taxonomy_redirects.py
"""

import os
import re
import unicodedata
import yaml

CONTENT_DIR = os.path.join(os.path.dirname(__file__), '..', 'content', 'posts')
STATIC_DIR = os.path.join(os.path.dirname(__file__), '..', 'static')

# WordPress category slugs that were set manually (not auto-generated from the name).
# Maps WordPress slug → Hugo category slug.
CATEGORY_SLUG_OVERRIDES = {
    'retour-xp': 'retour-dexpérience',
    'retour-d-experience': "retour-dexpérience",
}

REDIRECT_TEMPLATE = """\
<!DOCTYPE html>
<html lang="fr">
  <head>
    <!-- Generated by scripts/generate_wordpress_taxonomy_redirects.py -->
    <meta charset="utf-8">
    <title>Redirection…</title>
    <meta http-equiv="refresh" content="0; url={target}">
    <link rel="canonical" href="{target}">
    <meta name="robots" content="noindex">
    <script>
      window.location.replace("{target}" + window.location.search + window.location.hash);
    </script>
  </head>
  <body>
    <p>Cette URL WordPress a été déplacée vers <a href="{target}">{target}</a>.</p>
  </body>
</html>
"""


def wordpress_slugify(value: str) -> str:
    """Approximate WordPress slug generation: strip accents, remove
    apostrophes, replace non-alphanumeric characters with hyphens."""
    # Remove apostrophes (straight and curly) — WordPress drops them
    cleaned = re.sub(r"['\u2019\u2018]", '', value)
    # NFD decomposition then drop combining marks (strips accents)
    nfkd = unicodedata.normalize('NFKD', cleaned)
    ascii_str = ''.join(c for c in nfkd if not unicodedata.combining(c))
    # Replace anything that is not a letter, digit, or hyphen
    slug = re.sub(r'[^a-z0-9-]+', '-', ascii_str.lower())
    slug = re.sub(r'-{2,}', '-', slug).strip('-')
    return slug


def hugo_category_slug(value: str) -> str:
    """Hugo keeps accents but removes apostrophes."""
    return value.replace("'", '').replace("'", '').lower()


def extract_taxonomy_terms(content_dir: str):
    """Walk all .md files and return (tags, categories) sets."""
    tags, categories = set(), set()
    for root, _dirs, files in os.walk(content_dir):
        for fname in files:
            if not fname.endswith('.md'):
                continue
            path = os.path.join(root, fname)
            with open(path, encoding='utf-8') as fh:
                text = fh.read()
            m = re.match(r'^---\n(.*?)\n---', text, re.DOTALL)
            if not m:
                continue
            try:
                fm = yaml.safe_load(m.group(1))
            except Exception:
                continue
            if fm and isinstance(fm.get('tags'), list):
                tags.update(fm['tags'])
            if fm and isinstance(fm.get('categories'), list):
                categories.update(fm['categories'])
    return tags, categories


def write_redirect(directory: str, target: str):
    os.makedirs(directory, exist_ok=True)
    filepath = os.path.join(directory, 'index.html')
    with open(filepath, 'w', encoding='utf-8') as fh:
        fh.write(REDIRECT_TEMPLATE.format(target=target))


def main():
    tags, categories = extract_taxonomy_terms(CONTENT_DIR)
    print(f'Found {len(tags)} tags and {len(categories)} categories')

    tag_dir = os.path.join(STATIC_DIR, 'tag')
    cat_dir = os.path.join(STATIC_DIR, 'category')

    count = 0

    # /tag/ index → /tags/
    write_redirect(tag_dir, '/tags/')
    count += 1

    # Per-tag redirects: /tag/<wp-slug>/ → /tags/<hugo-slug>/
    for tag in sorted(tags):
        wp_slug = wordpress_slugify(tag)
        hugo_slug = tag.lower()  # Hugo uses the tag value as-is (lowercased)
        target = f'/tags/{hugo_slug}/'

        write_redirect(os.path.join(tag_dir, wp_slug), target)
        count += 1

        # /tag/<slug>-2/ was indexed by Google from the WordPress site (page 2 of
        # the tag archive, visible under some WordPress permalink configurations).
        # Redirect it to the first page — better than a 404.
        write_redirect(os.path.join(tag_dir, f'{wp_slug}-2'), target)
        count += 1

    # /category/ index → /categories/
    write_redirect(cat_dir, '/categories/')
    count += 1

    # Per-category redirects: /category/<wp-slug>/ → /categories/<hugo-slug>/
    for cat in sorted(categories):
        wp_slug = wordpress_slugify(cat)
        hugo_slug = hugo_category_slug(cat)
        target = f'/categories/{hugo_slug}/'

        write_redirect(os.path.join(cat_dir, wp_slug), target)
        count += 1

        # Same as tags: /category/<slug>-2/ was indexed by Google.
        write_redirect(os.path.join(cat_dir, f'{wp_slug}-2'), target)
        count += 1

    # Manual overrides for custom WordPress category slugs
    for wp_slug, hugo_slug in CATEGORY_SLUG_OVERRIDES.items():
        target = f'/categories/{hugo_slug}/'
        write_redirect(os.path.join(cat_dir, wp_slug), target)
        count += 1

    print(f'Generated {count} redirect pages in static/tag/ and static/category/')


if __name__ == '__main__':
    main()
